### ISSUE TITLE
sys.exit(1) should be called when a use fails

### ISSUE THREAD

**Issue by cclauss** [rootm0s/WinPwnage#45]
When __[-]__ is printed then WinPwnage should not exit with 0.  This will signal the calling script that a failure has occurred.
```
[-] Technique not compatible with this system.
The command "$RUN_WINPWNAGE -use -uac 1 /c/windows/system32/cmd.exe" exited with 0.
```
* https://travis-ci.com/rootm0s/WinPwnage/jobs/187405512#L229-L230
* https://travis-ci.com/rootm0s/WinPwnage/jobs/187405512#L313-L314
* https://travis-ci.com/rootm0s/WinPwnage/jobs/187405512#L330-L331
* https://travis-ci.com/rootm0s/WinPwnage/jobs/187405512#L347-L348

**Comment by rootm0s** [comment]
True, if it fails then it shouldnt return 0

**Comment by rootm0s** [comment]
Not sure if `sys.exit(1)` would break a applications flow if winpwnage is imported as a package...

**Comment by rootm0s** [comment]
Also, we cannot use `sys.exit(1)` inside the prints.py file since it will stop the auto-cleaning upon failure if it exits immediately. So I guess it has to be added to each function.

**Comment by cclauss** [comment]
No rush to solve this one...  Let's take time to find the best solution.

**Comment by rootm0s** [comment]
In **scanner.py** under the line `print_error('Technique not compatible with this system.')` we can return False, or 0 if you want. Shouldn't impact the functionality. 

This senario shouldn't happen in the first place since the scanner tells you what functions that is supposed to work. If you chose a function that is not compatible, then someone fucked up.
