### ISSUE TITLE
Bypassing UAC 

### ISSUE THREAD

**Issue by SK-ASIF-ALI** [rootm0s/WinPwnage#91]
Can we use this module for installation of an app like notepad++ as admin without uac prompt in a standard account. Or can we pass the username and password to install exe apps in  a machine silently...

**Comment by rootm0s** [comment]
In order to bypass UAC the user account has to be in Administrators group. 

If you have the username and password of a account that's administrator, you can use PsExec to install it as a different user or you can launch the actual process with "shift + right-click" and run it as a different user and specify the account details.

If you want to deploy software in your organisation I suggest to use a legit framework built to install apps like this one:
https://psappdeploytoolkit.com
